export type LyricsField = {
  song: string
  lyrics: Array<string>
}

export const VALID_GUESSES: Array<LyricsField> = [
  {
    lyrics: [
      'Jai Ho!',
      'Jai Ho',
      'I got shivers',
      'When you touch my face',
      "I'll make you hot",
      'Get all you got',
    ],
    song: 'A.R. Rahman ─ Jai Ho! (You Are My Destiny)',
  },
  {
    lyrics: [
      "There's a fire starting in my heart",
      "Reaching a fever pitch and it's bringing me out the dark",
      'Finally, I can see you crystal clear',
      "Go ahead and sell me out and I'll lay your shit bare",
      "See how I'll leave with every piece of you",
      "Don't underestimate the things that I will do",
    ],
    song: 'Adele ─ Rolling In The Deep',
  },
  {
    lyrics: [
      "I keep on fallin' in",
      'And outta love with you',
      'Sometimes I love ya, sometimes you make me blue',
      'Sometimes I feel good, at times I feel used',
      "Lovin' you, darlin', makes me so confused",
      "I keep on fallin' in and out",
    ],
    song: "Alicia Keys ─ Fallin'",
  },
  {
    lyrics: [
      'They tried to make me go to rehab, but I said, "No, no, no"',
      "Yes, I've been black, but when I come back, you'll know, know, know",
      "I ain't got the time and if my daddy thinks I'm fine",
      "He's tried to make me go to rehab, but I won't go, go, go",
      "I'd rather be at home with Ray",
      "I ain't got seventy days",
    ],
    song: 'Amy Winehouse ─ Rehab',
  },
  {
    lyrics: [
      'What you want, baby, I got it',
      'What you need, do you know I got it?',
      "All I'm askin' is for a little respect when you come home",
      '(Just a little bit) Hey baby',
      '(Just a little bit) when you get home',
      '(Just a little bit) mister',
    ],
    song: 'Aretha Franklin ─ Respect',
  },
  {
    lyrics: [
      "Hey, hey, you, you, I don't like your girlfriend",
      'No way, no way, I think you need a new one',
      'Hey, hey, you, you, I could be your girlfriend',
      'Hey, hey, you, you, I know that you like me',
      "No way, no way, you know it's not a secret",
      'Hey, hey, you, you, I want to be your girlfriend',
    ],
    song: 'Avril Lavigne ─ Girlfriend',
  },
  {
    lyrics: [
      "I don't need no TV",
      "I don't need no news",
      "All I need is a bumpin' beat",
      'To bump away my blues',
      "I don't give a damn what the people say",
      "I'm gonna do it my way, gonna do it my way",
    ],
    song: 'Basement Jaxx ─ Do Your Thing',
  },
  {
    lyrics: [
      'If I were a boy',
      'Even just for a day',
      "I'd roll out of bed in the morning",
      'And throw on what I wanted then go',
      'Drink beer with the guys',
      'And chase after girls',
    ],
    song: 'Beyoncé ─ If I Were a Boy',
  },
  {
    lyrics: [
      "Baby, can't you see I'm calling?",
      'A guy like you should wear a warning',
      "It's dangerous, I'm falling",
      "There's no escape, I can't wait",
      'I need a hit, baby, give me it',
      "You're dangerous, I'm lovin' it",
    ],
    song: 'Britney Spears ─ Toxic',
  },
  {
    lyrics: [
      'I threw a wish in the well',
      "Don't ask me, I'll never tell",
      'I looked to you as it fell',
      "And now you're in my way",
      'I trade my soul for a wish',
      'Pennies and dimes for a kiss',
    ],
    song: 'Carly Rae Jepsen ─ Call Me Maybe',
  },
  {
    lyrics: [
      "I'll seek you out",
      'Flay you alive',
      "One more word and you won't survive",
      "And I'm not scared of your stolen power",
      'I see right through you any hour',
      "I won't soothe your pain",
    ],
    song: 'Blue Foundation ─ Eyes on Fire',
  },
  {
    lyrics: [
      'Oh the shark, babe, has such teeth, dear',
      'And he shows them pearly white',
      'Just a jackknife has old Macheath, babe',
      'And he keeps it outta sight',
      'You know when that shark bites with his teeth, babe',
      'Scarlet billows start to spread',
    ],
    song: 'Bobby Darin ─ Mack the Knife',
  },
  {
  lyrics: [
    'The sun goes down, the stars come out',
    'And all that counts is here and now',
    'My universe will never be the same',
    "I'm glad you came (Came, came, came)",
    'You cast a spell on me, spell on me',
    'You hit me like the sky fell on me, fell on me',
  ],
  song: 'The Wanted ─ Glad You Came',
},
  {
  lyrics: [
    'Well you done done me in; you bet I felt it',
    "I tried to be chill but you're so hot that I melted",
    'I fell right through the cracks',
    "Now I'm trying to get back",
    'Before the cool done run out',
    "I'll be giving it my bestest",
  ],
  song: "Jason Mraz ─ I'm Yours",
},
  {
    lyrics: [
      "Right now, he's probably slow dancing",
      'With a bleached-blonde tramp',
      "And she's probably getting frisky",
      "Right now, he's probably buying her some fruity little drink",
      "'Cause she can't shoot a whiskey",
      "Right now, he's probably up behind her with a pool-stick",
    ],
    song: 'Carrie Underwood ─ Before He Cheats',
  },
  {
    lyrics: [
      'You know the bed feels warmer',
      "Sleepin' here alone (Sleepin' here alone)",
      'You know I dream in color',
      'And do the things I want (Do the things I want)',
      'You think you got the best of me',
      "Think you've had the last laugh",
    ],
    song: "Kelly Clarkson ─ Stronger (What Doesn't Kill You)",
  },
  {
    lyrics: [
      'Spinning around, spinning around',
      'Oh',
      "I'm spinning around, move out of my way",
      "I know you're feeling me 'cause you like it like this",
      "I'm breaking it down, I'm not the same",
      "I know you're feeling me 'cause you like it like this",
    ],
    song: 'Kylie Minogue ─ Spinning Around',
  },
  {
    lyrics: [
      'Party Rock',
      'Yeah',
      'Woo!',
      "Let's go!",
      'Party rockers in the house tonight',
      'Everybody just have a good time (Yeah)',
    ],
    song: 'LMFAO ─ Party Rock Anthem',
  },
  {
    lyrics: [
      'It doesn\\\'t matter if you love him, or capital "H-I-M" (M, M, M)',
      'Just put your paws up',
      "'Cause you were born this way, baby",
      'My mama told me when I was young',
      '"We are all born superstars"',
      'She rolled my hair and put my lipstick on',
    ],
    song: 'Lady Gaga ─ Born This Way',
  },
  {
  lyrics: [
    'I need to get my story straight',
    'My friends are in the bathroom',
    'Getting higher than the empire state',
    'My lover she is waiting for me',
    'Just across the bar',
    "My seat's been taken by some sunglasses",
  ],
  song: 'fun. ─ We Are Young (feat. Janelle Monáe)',
},
  {
  lyrics: [
    'Here we go again',
    'I kinda wanna be more than friends',
    'So take it easy on me',
    "I'm afraid you're never satisfied",
    'Here we go again',
    "We're sick like animals, we play pretend",
  ],
  song: 'Neon Trees ─ Animal',
},
  {
    lyrics: [
      'Well, sometimes, I go out by myself',
      'And I look across the water',
      "And I think of all the things, what you're doin'",
      'And in my head, I paint a picture',
      "'Cause since I've come home",
      "Well, my body's been a mess",
    ],
    song: 'Mark Ronson ─ Valerie (feat. Amy Winehouse) - Version Revisited',
  },
  {
    lyrics: [
      "Closed off from love, I didn't need the pain",
      'Once or twice was enough and it was all in vain',
      "Time starts to pass, before you know it you're frozen",
      "But somethin' happened for the very first time with you",
      "My heart melted to the ground, found somethin' true",
      "And everyone's lookin' 'round thinkin' I'm goin' crazy",
    ],
    song: 'Leona Lewis ─ Bleeding Love',
  },
    {
    lyrics: [
      'Ladies up in here tonight',
      'No fighting (We got the refugees up in here)',
      'No fighting',
      'No fighting',
      'Shakira, Shakira',
      'I never really knew that she could dance like this (Hey)',
    ],
    song: "Shakira ─ Hips Don't Lie (feat. Wyclef Jean)",
  },
    {
    lyrics: [
      "Robert's got a quick hand",
      "He'll look around the room, he won't tell you his plan",
      "He's got a rolled cigarette",
      "Hanging out his mouth, he's a cowboy kid",
      'Yeah, he found a six-shooter gun',
      "In his dad's closet with a box of fun things",
    ],
    song: 'Foster The People ─ Pumped Up Kicks',
  },
  {
    lyrics: [
      'Head underwater and they tell me',
      'To breathe easy for a while',
      'The breathing gets harder, even I know that',
      "Made room for me but it's too soon to see",
      "If I'm happy in your hands",
      "I'm unusually hard to hold onto",
    ],
    song: 'Sara Bareilles ─ Love Song',
  },
  {
    lyrics: [
      'I hopped off the plane at LAX',
      'With a dream and my cardigan',
      'Welcome to the land of fame excess (Woah)',
      'Am I gonna fit in?',
      'Jumped in the cab, here I am for the first time',
      'Look to my right, and I see the Hollywood sign',
    ],
    song: 'Miley Cyrus ─ Party In The U.S.A.',
  },
  {
    lyrics: [
      'I wanna boom bang bang with your body-o',
      'We gonna rough it up before we take it slow',
      'Girl, let me rock you rock you like a rodeo',
      '(it’s gonna be a bumpy ride)',
      'I wanna boom bang bang with your body-o',
      'We gonna rough it up before we take it slow',
    ],
    song: 'Mohombi ─ Bumpy Ride',
  },
  {
    lyrics: [
      'I came to dance, dance, dance, dance (Yeah)',
      "I hit the floor 'cause that's my plans, plans, plans, plans (Yeah)",
      "I'm wearing all my favorite brands, brands, brands, brands (Yeah)",
      'Give me some space for both my hands, hands, hands, hands, yeah, yeah',
      "'Cause it goes on and on and on",
      'And it goes on and on and on, yeah',
    ],
    song: 'Taio Cruz ─ Dynamite',
  },
  {
    lyrics: [
      'Wake up, blood-shot eye',
      'Struggle to memorize',
      'The way it felt between your thighs',
      'Pleasure that made you cry',
      'It feels so good to be bad',
      'Not worth the aftermath, after that, after that',
    ],
    song: 'Maroon 5 ─ Makes Me Wonder',
  },
  {
    lyrics: [
      "James Brown - It's A Man's, Man's, Man's World",
      "David Ruffin - Everything's Coming Up Love",
      "Ray Charles - I've Got A Woman",
      'Billy Stewart - I Do Love You',
      'Jerry Butler - Only The Strong Survive (Single Version)',
      "Barrett Strong - Money (That's What I Want)",
    ],
    song: 'Marvin Gaye ─ I Heard It Through The Grapevine - Single Version (Mono)',
  },
  {
    lyrics: [
      'The Shot',
      'Yeah, come on',
      '(Shake, shake)',
      "I'll take you home if you don't leave me at the front door (Leave me at the front door)",
      "Your body's cold, but girl, we're getting so warm",
      'And I was thinking of ways that I could get inside (Get inside)',
    ],
    song: 'Metro Station ─ Shake It',
  },
  {
    lyrics: [
      "I am unwritten, can't read my mind",
      "I'm undefined",
      "I'm just beginning, the pen's in my hand",
      'Ending unplanned',
      'Staring at the blank page before you',
      'Open up the dirty window',
    ],
    song: 'Natasha Bedingfield ─ Unwritten',
  },
  {
    lyrics: [
      "You're beautiful, that's for sure",
      "You'll never ever fade",
      "You're lovely, but it's not for sure",
      "That I won't ever change",
      'And though my love is rare',
      'Though my love is true',
    ],
    song: "Nelly Furtado ─ I'm Like A Bird",
  },
  {
    lyrics: [
      'One, two, three, uh!',
      "My baby don't mess around",
      'Because she loves me so, and this I know for sure (Uh)',
      'But does she really wanna',
      "But can't stand to see me walk out the door? (Ah)",
      "Don't try to fight the feeling",
    ],
    song: 'Outkast ─ Hey Ya!',
  },
  {
    lyrics: [
      'Hmm-mmm-mmm',
      'Whoa-oh-oh-oh',
      "It's always a good time",
      'Whoa-oh-oh-oh',
      "It's always a good time",
      'Woke up on the right side of the bed',
    ],
    song: 'Owl City ─ Good Time',
  },
  {
    lyrics: [
      'White knuckles',
      'And sweaty palms from hanging on too tight',
      'Clenched shut jaw',
      "I've got another headache again tonight",
      'Eyes on fire, eyes on fire',
      'And they burn from all the tears',
    ],
    song: 'P!nk ─ Blow Me (One Last Kiss)',
  },
  {
    lyrics: [
      'Yo, coming in with a sound fresher than cut grass',
      '(Fun starts)',
      'Second that we enter if you must ask',
      '(Rush past)',
      "Like you've forgotten your mind",
      'All the drivers all up our face like "Can I see your bus pass?"',
    ],
    song: 'Rizzle Kicks ─ Mama Do The Hump',
  },
  {
    lyrics: [
      "Man, it's a hot one",
      'Like seven inches from the midday sun',
      'I hear you whisper and the words melt everyone',
      'But you stay so cool',
      'My muñequita, my Spanish Harlem Mona Lisa',
      "You're my reason for reason, the step in my groove",
    ],
    song: 'Santana ─ Smooth (feat. Rob Thomas)',
  },
  {
    lyrics: [
      'Shake dat ting, miss Cana, Cana',
      'Shake dat ting, miss Annabella',
      'Shake dat ting, yo, Donna Donna',
      'Jodi and Rebecca',
      'Woman, get busy, jus shake dat booty nonstop',
      "When di beat drop, jus keep swingin' it",
    ],
    song: 'Sean Paul ─ Get Busy',
  },
  {
    lyrics: [
      "Boys call you sexy (What's up, sexy?)",
      "And you don't care what they say (Ha, ha)",
      'See, every time you turn around, they screaming your name',
      "Just call you sexy (What's up, sexy?)",
      "And you don't care what they say (Yeah)",
      'See, every time you turn around, they screaming your name',
    ],
    song: 'The Pussycat Dolls ─ When I Grow Up',
  },
  {
    lyrics: [
      'You never close your eyes anymore when I kiss your lips',
      "And there's no tenderness like before in your fingertips",
      "You're trying hard not to show it, (baby)",
      'But baby, baby I know it',
      "You've lost that lovin' feelin'",
      "Whoa, that lovin' feelin'",
    ],
    song: "The Righteous Brothers ─ You've Lost That Lovin' Feelin' - Single Version",
  },
  {
    lyrics: [
      "I'm gonna fight 'em off",
      "A seven nation army couldn't hold me back",
      "They're gonna rip it off",
      'Taking their time right behind my back',
      "And I'm talking to myself at night",
      "Because I can't forget",
    ],
    song: 'The White Stripes ─ Seven Nation Army',
  },
  {
    lyrics: [
      'Ayy, ayy, ayy',
      'Ayy, ayy, ayy',
      "I'm holding on your rope",
      'Got me ten feet off the ground',
      "And I'm hearing what you say",
      "But I just can't make a sound (Ayy, ayy, ayy)",
    ],
    song: 'Timbaland ─ Apologize',
  },
  {
    lyrics: [
      'Just a day, just an ordinary day',
      'Just trying to get by',
      'Just a boy, just an ordinary boy, but he was looking to the sky',
      'And as he asked if I would come along',
      'I started to realize',
      "That every day he finds just what he's looking for",
    ],
    song: 'Vanessa Carlton ─ Ordinary Day',
  },
  {
    lyrics: [
      'This land is your land and this land is my land',
      'From the California to the New York island',
      'From the redwood forest to the Gulf Stream waters',
      'This land was made for you and me',
      'As I went walking that ribbon of highway',
      'I saw above me that endless skyway',
    ],
    song: 'Woody Guthrie ─ This Land is Your Land',
  },
  {
    lyrics: [
      'Comme te pò capì chi te vò bene',
      'Si tu le parle miezzo americano?',
      "Quanno se fa l'ammore sotto 'a luna",
      "Comme te vene \\'ncapa \\'e di\\': \"I love you\"?",
      "Pa pa l'americano",
      "Pa pa l'americano",
    ],
    song: 'Yolanda Be Cool ─ We No Speak Americano',
  },
  {
    lyrics: [
      "Young girl, don't cry",
      "I'll be right here when your world starts to fall",
      "Young girl, it's alright",
      "Your tears will dry, you'll soon be free to fly, ooh",
      "When you're safe inside your room, you tend to dream",
      "Of a place where nothing's harder than it seems",
    ],
    song: 'Christina Aguilera ─ The Voice Within',
  },
  {
    lyrics: [
      'Will you count me in?',
      "I've been awake for a while now",
      "You've got me feeling like a child now",
      "'Cause every time I see your bubbly face",
      'I get the tingles in a silly place',
      'It starts in my toes and I crinkle my nose',
    ],
    song: 'Colbie Caillat ─ Bubbly',
  },
  {
    lyrics: [
      'Where is the moment we needed the most?',
      'You kick up the leaves and the magic is lost',
      'They tell me your blue skies fade to gray',
      "They tell me your passion's gone away",
      "And I don't need no carryin' on",
      'You stand in the line just to hit a new low',
    ],
    song: 'Daniel Powter ─ Bad Day',
  },
  {
    lyrics: [
      'Kelly, can you handle this?',
      'Michelle, can you handle this?',
      'Beyonce, can you handle this?',
      "I don't think they can handle this (Woo)",
      "Better move, 'cause we've arrived",
      "Lookin' sexy, lookin' fly",
    ],
    song: "Destiny's Child ─ Bootylicious",
  },
  {
    lyrics: [
      'A long, long time ago',
      'I can still remember',
      'How that music used to make me smile',
      'And I knew if I had my chance',
      'That I could make those people dance',
      "And maybe they'd be happy for a while",
    ],
    song: 'Don McLean ─ American Pie',
  },
  {
    lyrics: [
      'You must take the "A"-Train',
      'To go to sugar hill way up in Harlem',
      'If you miss the "A"-Train',
      "You'll find you missed the quickest way to Harlem",
      "Hurry - get on now it's coming",
      'Listen - to these rails a-humming - all board',
    ],
    song: 'Duke Ellington ─ Take the "A" Train',
  },
  {
    lyrics: [
      'Katie Casey was baseball mad',
      'Had the fever and had it bad',
      'Just to root for the home town crew',
      "Ev'ry sou",
      'Katie blew',
      'On a Saturday her young beau',
    ],
    song: 'Edward Meeker ─ Take Me Out To The Ball Game',
  },
  {
    lyrics: [
      'How can you see into my eyes like open doors?',
      "Leading you down into my core, where I've become so numb",
      "Without a soul, my spirit's sleeping somewhere cold",
      'Until you find it there and lead it back home',
      'Wake me up, wake me up inside',
      "I can't wake up, wake me up inside",
    ],
    song: 'Evanescence ─ Bring Me To Life',
  },
  {
    lyrics: [
      'I can feel the magic floating in the air',
      'Being with you gets me that way',
      "I watch the sunlight dance across your face and I've",
      'Never been this swept away',
      'All my thoughts just seem to settle on the breeze',
      "When I'm lying wrapped up in your arms",
    ],
    song: 'Faith Hill ─ Breathe',
  },
  {
    lyrics: [
      'I found my thrill on Blueberry Hill',
      'On Blueberry Hill, when I found you',
      'The moon stood still on Blueberry Hill',
      'And lingered until my dream came true',
      'The wind in the willow played',
      "Love's sweet melody",
    ],
    song: 'Fats Domino ─ Blueberry Hill',
  },
  {
    lyrics: [
      'Happiness hit her like a train on a track',
      'Coming towards her, stuck still no turning back',
      'She hid around corners, and she hid under beds',
      'She killed it with kisses, and from it she fled',
      'With every bubble she sank with a drink',
      'And washed it away down the kitchen sink',
    ],
    song: 'Florence + The Machine ─ Dog Days Are Over',
  },
  {
    lyrics: [
      "You know I'd fall apart without you",
      "I don't know how you do what you do",
      "'Cause everything that don't make sense about me",
      "Makes sense when I'm with you",
      "Like everything that's green, girl",
      'I need you',
    ],
    song: 'Hunter Hayes ─ Wanted',
  },
  {
    lyrics: [
      '(Monáe and Leftfoot)',
      'Whoa (Ye-yeah)',
      'Another day (Da-ba-dee, Náe)',
      'I take your pain away (Huh, come on)',
      'Some people talk about ya like they know all about ya',
      'When you get down, they doubt ya',
    ],
    song: 'Janelle Monáe ─ Tightrope',
  },
  {
    lyrics: [
      'Go!',
      'So one, two, three',
      'Take my hand and come with me',
      'Because you look so fine',
      'That I really wanna make you mine',
      'I said, you look so fine',
    ],
    song: 'Jet ─ Are You Gonna Be My Girl',
  },
  {
    lyrics: [
      'The other night, dear, as I lay sleeping',
      'I dreamed I held you in my arms',
      'But when I awoke, dear, I was mistaken',
      'And I hung my head and cried',
      'You are my sunshine, my only sunshine',
      'You make me happy when skies are grey',
    ],
    song: 'Jimmie Davis ─ You Are My Sunshine',
  },
  {
    lyrics: [
      "It's not a silly little moment",
      "It's not the storm before the calm",
      'This is the deep and dying breath of',
      "This love that we've been working on",
      "Can't seem to hold you like I want to",
      'So I can feel you in my arms',
    ],
    song: 'John Mayer ─ Slow Dancing in a Burning Room',
  },
  {
    lyrics: [
      'I hurt myself today',
      'To see if I still feel',
      'I focus on the pain',
      "The only thing that's real",
      'The needle tears a hole',
      'The old familiar sting',
    ],
    song: 'Johnny Cash ─ Hurt',
  },
  {
    lyrics: [
      'Somewhere over the rainbow',
      'Way up high',
      "There's a land that I heard of",
      'Once in a lullaby',
      'Somewhere over the rainbow',
      'Skies are blue',
    ],
    song: 'Judy Garland ─ Over The Rainbow',
  },
  {
    lyrics: [
      '"While the storm clouds gather far across the sea',
      "Let us swear allegiance to a land that's free",
      'Let us all be grateful for a land so fair',
      'As we raise our voices in a solemn prayer. "',
      'God bless America',
      'Land that I love',
    ],
    song: 'Kate Smith ─ God Bless America',
  },
    {
    lyrics: [
      'Days like this, I want to drive away',
      'Pack my bags and watch your shadow fade',
      'You chewed me up and spit me out',
      'Like I was poison in your mouth',
      'You took my light, you drained me down',
      'But that was then and this is now',
    ],
    song: 'Katy Perry ─ Part Of Me',
  },
]
